const dictionary = {
    "abierto": "Que no está cerrado o que está disponible.",
    "abrir": "Hacer que algo pase de un estado cerrado a uno abierto.",
    "acerca": "Indica proximidad o relación con algo.",
    "acompañar": "Estar al lado de alguien o algo como compañía.",
    "acción": "Movimiento o actividad que realiza un ser humano.",
    "alegría": "Estado de ánimo de satisfacción y placer.",
    "amar": "Sentir amor por alguien o algo.",
    "animal": "Ser vivo que no es vegetal ni humano.",
    "antiguo": "Que pertenece a un tiempo pasado.",
    "aprender": "Adquirir conocimientos o habilidades.",
    "aprecio": "Valor o estima que se tiene por alguien o algo.",
    "arte": "Expresión de la creatividad humana en diversas formas.",
    "asistente": "Persona que ayuda o apoya a otra.",
    "atención": "Acción de prestar cuidado o interés en algo.",
    "aula": "Sala destinada para la enseñanza y el aprendizaje.",
    "automóvil": "Vehículo de motor utilizado para el transporte.",
    "avanzar": "Moverse hacia adelante o progresar.",
    "ayer": "El día anterior al actual.",
    "almuerzo": "Comida que se consume al mediodía.",
    "ansiedad": "Estado de inquietud o preocupación.",
    "aspecto": "Apariencia o apariencia externa de algo.",
    "así": "De esta manera o de tal modo.",
    "autor": "Persona que crea una obra literaria o artística.",
    "autoridad": "Poder o derecho de mandar o tomar decisiones.",
    "admirar": "Sentir respeto o estima hacia algo o alguien.",
    "adversidad": "Situación desfavorable o difícil.",

    "bailar": "Mover el cuerpo al ritmo de la música.",
    "bajo": "De poca altura o menor en comparación.",
    "banco": "Entidad financiera donde se realizan transacciones de dinero.",
    "barco": "Embarcación utilizada para navegar en el agua.",
    "batería": "Conjunto de dispositivos que almacenan energía eléctrica.",
    "bebida": "Líquido que se consume para saciar la sed.",
    "bello": "Que tiene belleza; atractivo o hermoso.",
    "bien": "En un estado positivo o satisfactorio.",
    "bocina": "Dispositivo que emite sonido o alarma.",
    "bola": "Objeto redondo que puede rodar.",
    "bosque": "Área grande cubierta de árboles y vegetación.",
    "brillante": "Que emite o refleja mucha luz.",
    "broma": "Acción o comentario humorístico.",
    "burbuja": "Esfera de aire atrapada en un líquido.",
    "búsqueda": "Acción de intentar encontrar algo.",
    "cuerpo": "La estructura física de un ser humano o animal.",
    "bajo": "Instrumento musical de cuerda de tono grave.",
    "balón": "Esférico, utilizado en varios deportes.",
    "bando": "Grupo que comparte una misma ideología o causa.",
    "batalla": "Conflicto armado entre fuerzas opuestas.",
    "banco": "Mueble o asiento largo sin respaldo.",
    "bajo": "Parte inferior o más baja de algo.",
    "bajo": "Instrumento musical de tono grave.",
    "bailarín": "Persona que se dedica a bailar profesionalmente.",
    "billete": "Documento que representa una cantidad de dinero.",

    "casa": "Edificio o lugar donde vive una persona.",
    "comida": "Sustancia que las personas y animales consumen para nutrirse.",
    "coche": "Vehículo terrestre de cuatro ruedas utilizado para el transporte de personas.",
    "cielo": "Espacio visible sobre la Tierra donde están las nubes y el sol.",
    "correr": "Desplazarse rápidamente utilizando las piernas.",
    "computadora": "Máquina electrónica que procesa datos y realiza cálculos.",
    "cultura": "Conjunto de costumbres, creencias y valores de una sociedad.",
    "corazón": "Órgano muscular que bombea sangre por el cuerpo.",
    "ciencia": "Conjunto de conocimientos sistematizados sobre un área determinada.",
    "crédito": "Dinero que se presta o se recibe a cambio de un compromiso de pago.",
    "carácter": "Conjunto de rasgos que definen a una persona.",
    "calor": "Forma de energía que se manifiesta como aumento de temperatura.",
    "calidad": "Grado de excelencia de algo.",
    "creatividad": "Capacidad de crear y generar ideas originales.",
    "conocimiento": "Información y habilidades adquiridas a través de la experiencia.",
    "cuidado": "Atención que se presta a algo o a alguien.",
    "cobarde": "Persona que muestra falta de valentía.",
    "caballo": "Animal mamífero usado para transporte y trabajo.",
    "cabeza": "Parte superior del cuerpo que contiene el cerebro y los sentidos.",
    "canción": "Composición musical con letra.",
    "capacidad": "Máximo nivel de rendimiento o producción.",
    "camino": "Ruta o vía por la que se transita.",
    "ciencia": "Sistema de conocimiento basado en la observación y la experimentación.",
    "cálido": "Que tiene una temperatura alta o moderada.",
    "cierre": "Acción de cerrar algo.",

    "día": "Periodo de 24 horas; el tiempo entre el amanecer y el anochecer.",
    "dormir": "Estado de reposo en el que una persona o animal descansa.",
    "dinero": "Medio de intercambio generalmente aceptado para bienes y servicios.",
    "decisión": "Elección que se toma entre varias opciones.",
    "dibujo": "Representación gráfica de un objeto o idea.",
    "desarrollo": "Proceso de crecimiento o evolución de algo.",
    "destino": "Lugar hacia el que se dirige alguien o algo.",
    "dificultad": "Grado de complicación o esfuerzo que requiere algo.",
    "dirección": "Indicaciones sobre cómo llegar a un lugar.",
    "diversión": "Actividades que proporcionan entretenimiento y alegría.",
    "decoro": "Comportamiento que se ajusta a las normas de la sociedad.",
    "deseo": "Anhelo de poseer algo o de que suceda algo.",
    "diálogo": "Conversación entre dos o más personas.",
    "detalles": "Aspectos o características específicas de algo.",
    "diseño": "Plan o proyecto que se elabora para crear algo.",
    "dificil": "Que presenta complicaciones o que no es fácil.",
    "doctor": "Profesional de la medicina que trata enfermedades.",
    "data": "Información recopilada y organizada.",
    "deber": "Responsabilidad o compromiso que se tiene con algo.",
    "dependencia": "Estado de necesitar algo o a alguien.",
    "descubrimiento": "Hallazgo de algo que estaba oculto o desconocido.",
    "disfrutar": "Experimentar placer o satisfacción.",
    "duración": "Tiempo durante el cual ocurre algo.",
    "deporte": "Actividad física que se realiza de manera competitiva o recreativa.",
    "destreza": "Habilidad o capacidad para hacer algo.",

    "escribir": "Representar palabras o ideas mediante símbolos o letras.",
    "escuchar": "Prestar atención a lo que alguien dice o a un sonido.",
    "educación": "Proceso de adquirir conocimientos y habilidades.",
    "esfuerzo": "Trabajo o dedicación para lograr algo.",
    "emoción": "Sentimiento intenso que se experimenta ante una situación.",
    "empresa": "Organización que realiza actividades económicas.",
    "experiencia": "Conocimiento adquirido a través de la práctica.",
    "esperanza": "Confianza en que algo bueno sucederá.",
    "estrella": "Cuerpo celeste que brilla con luz propia en el cielo.",
    "elección": "Decisión entre varias opciones o candidatos.",
    "equipo": "Conjunto de personas que trabajan juntas para un objetivo.",
    "energía": "Capacidad de realizar trabajo o producir movimiento.",
    "etapa": "Fase o período de un proceso.",
    "evolución": "Cambio gradual en algo a lo largo del tiempo.",
    "entender": "Comprender el significado de algo.",
    "especialidad": "Área específica de conocimiento o habilidad.",
    "estilo": "Manera particular de hacer algo.",
    "etiqueta": "Reglas de comportamiento social.",
    "efecto": "Resultado o consecuencia de una acción.",
    "entorno": "Circunstancias o ambiente que rodean a alguien o algo.",
    "éxito": "Logro de un objetivo o meta.",
    "ejemplo": "Caso que sirve para ilustrar o explicar algo.",
    "elemento": "Parte o componente de un todo.",
    "evaluación": "Proceso de valorar o juzgar algo.",
    "espejo": "Superficie que refleja imágenes.",
    "examen": "Prueba para evaluar conocimientos o habilidades.",

    "familia": "Grupo de personas relacionadas por parentesco.",
    "felicidad": "Estado de ánimo de satisfacción y alegría.",
    "fruta": "Alimento producido por ciertas plantas que contiene semillas y es comestible.",
    "flor": "Parte de una planta que es colorida y produce semillas o frutos.",
    "fuego": "Reacción química que produce luz y calor.",
    "fácil": "Que no requiere mucho esfuerzo o dificultad.",
    "futuro": "Tiempo que aún no ha llegado.",
    "fabrica": "Lugar donde se producen bienes.",
    "fútbol": "Deporte en el que dos equipos juegan para marcar goles con una pelota.",
    "formación": "Proceso de desarrollo y aprendizaje.",
    "frecuencia": "Número de veces que ocurre un evento en un período determinado.",
    "feria": "Evento público donde se venden productos o se realizan actividades recreativas.",
    "firmeza": "Cualidad de ser fuerte o estable.",
    "física": "Ciencia que estudia la materia y la energía.",
    "fidelidad": "Lealtad o compromiso hacia alguien o algo.",
    "figura": "Forma o contorno de un objeto.",
    "fisonomía": "Aspecto o características físicas de una persona.",
    "filosofía": "Estudio de las cuestiones fundamentales de la existencia y el conocimiento.",
    "forzar": "Imponer una acción o condición a alguien o algo.",
    "falsedad": "Cualidad de ser falso o engañoso.",
    "física": "Ciencia que estudia la materia y sus interacciones.",
    "fama": "Reconocimiento o reputación pública.",
    "factor": "Elemento que contribuye a un resultado.",
    "frío": "Temperatura baja.",
    "función": "Rol o propósito que cumple algo.",
    "fomento": "Acción de promover o impulsar algo.",

    "gato": "Mamífero doméstico pequeño con garras y agilidad.",
    "grande": "De gran tamaño o importancia.",
    "guerra": "Conflicto armado entre grupos o naciones.",
    "gente": "Conjunto de personas que comparten un lugar o actividad.",
    "globo": "Esfera llena de aire o gas, utilizada para decorar o jugar.",
    "guitarra": "Instrumento musical de cuerda que se toca con los dedos o un pua.",
    "gel": "Sustancia viscosa que se utiliza en cosméticos y productos de limpieza.",
    "gravedad": "Fuerza que atrae los cuerpos hacia el centro de la Tierra.",
    "gesto": "Movimiento de una parte del cuerpo que expresa una idea o emoción.",
    "golf": "Deporte que consiste en golpear una pelota hacia un hoyo en el menor número de golpes.",
    "ganar": "Obtener un premio, ventaja o victoria en una competencia.",
    "guardar": "Conservar algo en un lugar seguro.",
    "grupo": "Conjunto de personas o cosas que tienen algo en común.",
    "gusto": "Sentido que permite percibir sabores.",
    "galaxia": "Conjunto enorme de estrellas, polvo y gas que se mantienen unidos por la gravedad.",
    "gafas": "Objeto que se usa para mejorar la visión o proteger los ojos.",
    "guía": "Persona o documento que ayuda a dirigir o informar.",
    "gloria": "Reconocimiento y alabanza por logros o virtudes.",
    "gemelos": "Personas que nacen al mismo tiempo de un mismo embarazo.",
    "gimnasia": "Actividad física que mejora la condición física y la flexibilidad.",
    "gráfico": "Representación visual de datos o información.",
    "generación": "Conjunto de personas nacidas y viviendo aproximadamente en el mismo período.",
    "gentileza": "Acto de ser amable o considerado con los demás.",
    "gusto": "Preferencia o inclinación hacia algo.",
    "gama": "Conjunto de elementos o posibilidades en una categoría específica.",

    "hogar": "Lugar donde vive una persona o una familia.",
    "hombre": "Ser humano masculino adulto.",
    "hora": "Unidad de tiempo que equivale a 60 minutos.",
    "hospital": "Institución donde se brindan servicios médicos.",
    "humor": "Estado de ánimo o disposición emocional.",
    "historia": "Estudio de eventos pasados y su registro.",
    "héroe": "Persona admirada por sus acciones valientes o nobles.",
    "horizonte": "Línea donde la tierra y el cielo parecen encontrarse.",
    "habilidad": "Capacidad para realizar algo de manera efectiva.",
    "hermosa": "Que tiene belleza; atractivo o agradable a la vista.",
    "hecho": "Algo que ha ocurrido o que es cierto.",
    "hielo": "Agua congelada en estado sólido.",
    "huésped": "Persona que se queda en casa ajena.",
    "herencia": "Conjunto de bienes o derechos que se transmiten de una generación a otra.",
    "horizonte": "Línea que se forma donde se encuentra la tierra con el cielo.",
    "huevo": "Óvulo de los animales, especialmente de las aves.",
    "humo": "Conjunto de partículas sólidas y gases que se producen al quemar algo.",
    "hablar": "Comunicar ideas o pensamientos usando palabras.",
    "hacia": "Indica dirección o movimiento hacia un lugar.",
    "hacia": "Que muestra inclinación o tendencia hacia algo.",
    "honor": "Reconocimiento de la dignidad y el respeto.",
    "hermano": "Persona que comparte uno o ambos padres con otra.",
    "hombre": "Ser humano masculino.",
    "historia": "Narración de eventos pasados.",
    "hazaña": "Acción notable y valiente.",
    "habitat": "Entorno natural donde vive una especie.",

    "isla": "Porción de tierra rodeada de agua por todas partes.",
    "infinito": "Sin límites; que no tiene fin.",
    "inteligencia": "Capacidad de aprender, entender y razonar.",
    "investigación": "Acción de indagar o explorar un tema o problema.",
    "inclusión": "Acción de incluir a alguien o algo dentro de un grupo.",
    "inmenso": "Que es muy grande o extenso.",
    "ideología": "Conjunto de ideas y valores que caracterizan a un grupo.",
    "impresión": "Efecto producido en la mente o los sentidos.",
    "instante": "Momento breve o puntual en el tiempo.",
    "innovación": "Introducción de novedades o mejoras en un ámbito.",
    "información": "Datos organizados que tienen significado.",
    "intención": "Propósito o finalidad de una acción.",
    "instrucción": "Conjunto de indicaciones o enseñanzas.",
    "invitación": "Propuesta para que alguien asista a un evento.",
    "inmediato": "Que sucede sin demora; inmediato.",
    "inquietud": "Estado de agitación o desasosiego.",
    "integridad": "Cualidad de ser completo y coherente.",
    "intensidad": "Grado de fuerza o energía de algo.",
    "inmunidad": "Capacidad del organismo para resistir enfermedades.",
    "interpretación": "Acción de explicar o dar sentido a algo.",
    "índice": "Lista o relación que organiza información.",
    "impulso": "Fuerza que provoca un movimiento.",
    "ítem": "Elemento o unidad en una lista o catálogo.",
    "ilusión": "Percepción engañosa de la realidad.",
    "inspiración": "Estimulación de la creatividad o el pensamiento.",
    "interacción": "Acción recíproca entre dos o más elementos.",

    "jardín": "Terreno cultivado con plantas, flores y árboles.",
    "jirafa": "Mamífero herbívoro, conocido por su largo cuello y patas.",
    "juego": "Actividad recreativa que se realiza para entretenimiento o diversión.",
    "joven": "Persona que está en la etapa de la juventud.",
    "juez": "Persona que tiene autoridad para tomar decisiones en un juicio.",
    "joya": "Objeto decorativo, generalmente hecho de metales preciosos y piedras.",
    "jabón": "Sustancia utilizada para lavar y limpiar.",
    "juguete": "Objeto con el que juegan los niños.",
    "japonés": "Relativo a Japón o a su cultura; también se refiere al idioma.",
    "jardinería": "Actividad de cultivar plantas y cuidar jardines.",
    "jamón": "Carne de cerdo curada.",
    "jirón": "Pedazo o trozo de algo que se ha rasgado.",
    "jubilación": "Estado de retiro del trabajo, generalmente por edad.",
    "juventud": "Período de la vida entre la niñez y la adultez.",
    "justicia": "Principio moral que busca la equidad y el respeto a los derechos.",
    "jugador": "Persona que participa en un juego o deporte.",
    "juegos": "Actividades recreativas que pueden ser competitivas o de entretenimiento.",
    "jardín": "Espacio al aire libre destinado al cultivo de plantas.",
    "jengibre": "Planta cuyas raíces son utilizadas como especia y medicina.",
    "jota": "Baile y música tradicional de algunas regiones de España.",
    "joyero": "Caja o estuche para guardar joyas.",
    "juicio": "Proceso legal para determinar la culpabilidad o inocencia de alguien.",
    "juguetón": "Que es juguetón o le gusta jugar.",
    "judo": "Arte marcial de origen japonés que enfatiza el lanzamiento y la inmovilización.",
    "jaula": "Estructura cerrada para mantener animales.",

    "kiwi": "Fruta comestible, de piel marrón y pulpa verde, rica en vitamina C.",
    "kilo": "Unidad de medida que equivale a mil gramos.",
    "kilómetro": "Unidad de medida de longitud que equivale a mil metros.",
    "karate": "Arte marcial de origen japonés que utiliza golpes y patadas.",
    "kárate": "Disciplina de combate sin armas que se centra en la autodefensa.",
    "kiosco": "Estructura pequeña donde se venden periódicos, alimentos u otros productos.",
    "karma": "Concepto en algunas filosofías que implica que las acciones de una persona influyen en su futuro.",
    "koala": "Marsupial australiano conocido por su pelaje gris y su dieta de hojas de eucalipto.",
    "ketchup": "Salsa hecha principalmente de tomate, utilizada como condimento.",
    "kilovatio": "Unidad de medida de potencia que equivale a mil vatios.",
    "kinesiología": "Ciencia que estudia el movimiento humano y su relación con la salud.",
    "kermés": "Fiesta o evento con actividades recreativas y venta de productos para recaudar fondos.",
    "katana": "Espada japonesa con una hoja larga y curva.",
    "karisma": "Atractivo personal o encanto que tiene una persona para influir en otros.",
    "kefir": "Bebida fermentada hecha a partir de leche o agua, rica en probióticos.",
    "kilim": "Tapiz o alfombra tejida a mano, típica de algunas culturas orientales.",
    "kevin": "Nombre propio que puede referirse a una persona.",
    "kilo": "Término informal para referirse a un kilogramo.",
    "kola": "Fruto de un árbol de la región tropical, usado en la elaboración de bebidas.",
    "kinesis": "Movimiento de un organismo en respuesta a un estímulo.",
    "karst": "Formación geológica caracterizada por paisajes de relieve irregular.",
    "kibutz": "Asentamiento agrícola colectivo en Israel.",
    "kontra": "Término musical que se refiere a una parte o sección en una pieza.",
    "kronos": "Concepto del tiempo en la mitología griega.",
    "kaká": "Nombre de un famoso futbolista brasileño.",
    "kaiser": "Término alemán que significa emperador.",

    "luz": "Radiación electromagnética que permite la visión.",
    "libro": "Conjunto de hojas impresas o manuscritas encuadernadas.",
    "lago": "Cuerpo de agua dulce o salada rodeado de tierra.",
    "luna": "Satélite natural de la Tierra.",
    "lápiz": "Utensilio para escribir o dibujar, hecho de madera y grafito.",
    "lengua": "Órgano muscular en la boca, utilizado para hablar y degustar.",
    "león": "Mamífero carnívoro conocido como el rey de la selva.",
    "leche": "Líquido blanco producido por las glándulas mamarias de los mamíferos.",
    "luz": "Fenómeno físico que permite ver los objetos.",
    "lago": "Cuerpo de agua de gran extensión, generalmente de agua dulce.",
    "libertad": "Estado de ser libre y no estar en prisión o bajo control.",
    "lápiz": "Instrumento de escritura con una mina de grafito.",
    "lámpara": "Dispositivo que produce luz artificial.",
    "luz": "Forma de energía que hace visibles los objetos.",
    "lección": "Parte de un conjunto de enseñanzas o clases.",
    "línea": "Conjunto de puntos que se extienden en una dirección.",
    "librería": "Establecimiento donde se venden libros.",
    "locomotora": "Vehículo que tira de un tren.",
    "laboratorio": "Lugar equipado para realizar experimentos o investigaciones.",
    "lujo": "Estado de vivir en riqueza o comodidad.",
    "lucha": "Conflicto físico o mental entre dos o más partes.",
    "largo": "Que tiene una extensión considerable en el espacio.",
    "límite": "Línea que marca el final de un área o espacio.",
    "lago": "Cuerpo de agua rodeado de tierra.",
    "ley": "Regla o norma establecida por una autoridad.",

    "música": "Arte de combinar sonidos para crear melodías y ritmos.",
    "mesa": "Mueble con una superficie plana sostenido por patas.",
    "mar": "Gran masa de agua salada que cubre parte de la superficie terrestre.",
    "madre": "Mujer que ha dado a luz o tiene hijos.",
    "mundo": "El planeta Tierra y sus habitantes.",
    "mirar": "Fijar la vista en algo.",
    "miel": "Sustancia dulce producida por las abejas.",
    "mañana": "Parte del día que comienza al amanecer y termina al mediodía.",
    "mascota": "Animal que se tiene en casa por compañía o entretenimiento.",
    "maestro": "Persona que enseña o instruye a otros.",
    "mujer": "Ser humano femenino adulto.",
    "madera": "Material obtenido de los árboles, utilizado en construcción y muebles.",
    "memoria": "Capacidad de recordar información y experiencias.",
    "mariposa": "Insecto con alas grandes y coloridas.",
    "medicina": "Sustancia o tratamiento utilizado para curar enfermedades.",
    "matemáticas": "Ciencia que estudia los números, las formas y las relaciones entre ellos.",
    "milagro": "Suceso extraordinario que se considera fuera de las leyes naturales.",
    "murmullo": "Sonido bajo y confuso que producen varias personas al hablar.",
    "modo": "Manera en que se realiza algo.",
    "murallas": "Paredes grandes que rodean una ciudad o fortaleza.",
    "motivo": "Razón o causa que impulsa a realizar algo.",
    "metáfora": "Comparación implícita entre dos cosas diferentes.",
    "maratón": "Carrera de larga distancia, generalmente de 42.195 kilómetros.",
    "misterio": "Situación o cosa que no se entiende o explica fácilmente.",
    "mago": "Persona que practica la magia o ilusionismo.",

    "nube": "Conjunto de pequeñas gotas de agua suspendidas en la atmósfera.",
    "noche": "Período del día cuando no hay luz solar.",
    "niño": "Persona de poca edad, generalmente menor de 12 años.",
    "naturaleza": "Conjunto de elementos y fuerzas del mundo físico.",
    "nombre": "Palabra que designa a una persona, lugar o cosa.",
    "nave": "Embarcación grande diseñada para viajar por mar.",
    "negocio": "Actividad económica que implica la compra y venta de bienes o servicios.",
    "nacionalidad": "Condición de pertenecer a una nación.",
    "narrativa": "Relato de una serie de eventos, ya sean reales o ficticios.",
    "noticia": "Información sobre eventos recientes o relevantes.",
    "número": "Símbolo que representa una cantidad o posición en una secuencia.",
    "nacer": "Comenzar la vida al salir del útero materno.",
    "nube": "Conjunto visible de pequeñas gotas de agua o cristales de hielo en la atmósfera.",
    "narrador": "Persona que cuenta una historia.",
    "novela": "Obra literaria de ficción en prosa.",
    "nobleza": "Clase social privilegiada, generalmente hereditaria.",
    "nutrición": "Conjunto de procesos mediante los cuales los organismos asimilan alimentos.",
    "negación": "Rechazo o oposición a algo.",
    "nexo": "Vínculo o conexión entre dos o más cosas.",
    "naciente": "Que está comenzando o en sus primeras etapas.",
    "navegación": "Acción de planear y seguir un rumbo en el mar o en el aire.",
    "novedad": "Cosa nueva o reciente.",
    "narciso": "Planta con flores amarillas o blancas, también nombre de un personaje mitológico.",
    "narrativa": "Género literario que incluye la narración de historias.",
    "notorio": "Que es evidente o conocido por todos.",

    "ñandú": "Ave grande y no voladora originaria de América del Sur.",
    "ñu": "Mamífero herbívoro de grandes dimensiones, conocido por sus migraciones.",
    "ñoño": "Persona que es muy tímida o que muestra falta de interés en lo que la rodea.",
    "ñame": "Raíz comestible de varias plantas, similar a la batata.",
    "ñapa": "Regalo o extra que se da al comprar algo.",
    "ñoñería": "Cualidad de ser ñoño; actitudes infantiles o exageradas.",
    "ñato": "Que tiene la nariz achatada o corta.",
    "ñus": "Plural de ñu, mamífero migratorio.",
    "ñuñu": "Término usado en algunos lugares para referirse a un niño o un pequeño.",
    "ñandutí": "Encaje típico de Paraguay, hecho a mano.",
    "ñangara": "Palabra utilizada en algunas regiones para referirse a una persona de carácter fuerte.",
    "ñuño": "Término regional que puede referirse a un niño o joven.",
    "ñandú": "Ave corredora similar al avestruz.",
    "ñapa": "Regalo o extra que se añade a una compra.",
    "ñus": "Mamífero que vive en manadas en África.",
    "ñapanga": "Planta tropical de la familia de las palmeras.",
    "ñor": "Expresión coloquial para referirse a un hermano o amigo.",
    "ñora": "Palabra que se usa para referirse a una mujer de carácter fuerte.",
    "ñengue": "Un tipo de música típica de algunas regiones.",
    "ñato": "Que tiene la nariz chata o aplastada.",
    "ñangotado": "Que está en una posición de sumisión o respeto.",
    "ñoño": "Se refiere a alguien que es poco interesante o aburrido.",
    "ñoras": "Plural de ñora, mujer de carácter fuerte.",
    "ñoñez": "Cualidad de ser ñoño.",

    "oído": "Órgano del sentido de la audición.",
    "olla": "Recipiente utilizado para cocinar alimentos.",
    "orquídea": "Planta con flores grandes y llamativas, apreciadas en jardinería.",
    "océano": "Extensa masa de agua salada que cubre gran parte de la Tierra.",
    "oso": "Mamífero grande y carnívoro que vive en diversas regiones del mundo.",
    "olla": "Recipiente profundo utilizado para cocinar.",
    "origen": "Punto o lugar de donde algo proviene.",
    "obra": "Trabajo artístico, literario o de construcción.",
    "ojos": "Órganos de la vista.",
    "ocultar": "Esconder algo de la vista o del conocimiento.",
    "olla": "Recipiente utilizado para hervir alimentos.",
    "octubre": "Mes del año que sigue a septiembre.",
    "óptica": "Ciencia que estudia la luz y su comportamiento.",
    "oficina": "Lugar de trabajo donde se realizan actividades administrativas.",
    "opción": "Posibilidad de elegir entre varias alternativas.",
    "obvio": "Que es evidente o claro.",
    "obesidad": "Condición de tener un exceso de grasa corporal.",
    "olivo": "Árbol cuyo fruto es la aceituna, utilizado para hacer aceite.",
    "orgullo": "Sentimiento de satisfacción por los logros propios o ajenos.",
    "oeste": "Dirección opuesta al este.",
    "oro": "Metal precioso de color amarillo brillante.",
    "ornamento": "Objeto decorativo utilizado para embellecer.",
    "ocurrencia": "Sucedido o evento inesperado.",
    "oración": "Conjunto de palabras que expresan una idea completa.",
    "oportunidad": "Circunstancia favorable para realizar algo.",

    "palabra": "Conjunto de letras que tiene un significado.",
    "paz": "Estado de tranquilidad y armonía en una sociedad.",
    "pájaro": "Animal vertebrado que tiene plumas y alas.",
    "pintura": "Arte de aplicar color a una superficie mediante diversos métodos.",
    "planta": "Organismo vegetal que crece en el suelo.",
    "película": "Obra cinematográfica que cuenta una historia a través de imágenes.",
    "persona": "Ser humano considerado individualmente.",
    "pueblo": "Conjunto de personas que viven en una misma comunidad.",
    "prenda": "Artículo de ropa que se lleva puesto.",
    "papel": "Material delgado utilizado para escribir o imprimir.",
    "poesía": "Expresión artística de la belleza mediante palabras en verso.",
    "puerta": "Abertura en un muro que permite el acceso a un espacio.",
    "pelota": "Objeto esférico utilizado en diversos deportes y juegos.",
    "pintor": "Persona que se dedica a la pintura.",
    "plaza": "Espacio público en una ciudad, frecuentemente con áreas verdes.",
    "paz": "Condición de no haber guerra o conflicto.",
    "paleta": "Herramienta usada en pintura para mezclar colores.",
    "plato": "Vajilla utilizada para servir alimentos.",
    "piscina": "Estructura diseñada para contener agua y ser utilizada para nadar.",
    "plomo": "Metal pesado de color gris, utilizado en diversas aplicaciones.",
    "piedra": "Material sólido que forma parte de la corteza terrestre.",
    "pasta": "Comida elaborada con harina y agua, como los fideos.",
    "profesor": "Persona que enseña, especialmente en una escuela o universidad.",
    "prueba": "Examen o test para verificar conocimientos o habilidades.",
    "preocupación": "Estado de inquietud o ansiedad sobre algo.",

    "queso": "Producto lácteo obtenido de la cuajada de la leche.",
    "quinto": "Número cinco en una serie ordenada.",
    "química": "Ciencia que estudia la composición, estructura y propiedades de la materia.",
    "quijote": "Personaje literario famoso de la obra de Cervantes, símbolo de idealismo.",
    "química": "Ciencia que estudia la materia y sus transformaciones.",
    "quinto": "Que ocupa el lugar número cinco en una serie.",
    "quimera": "Ser mitológico o fantasioso; también se refiere a un sueño imposible.",
    "quinto": "Fracción de un total dividido en cinco partes iguales.",
    "quasar": "Objeto astronómico extremadamente brillante y lejano.",
    "quebrada": "Desfiladero o lugar por donde pasa un río.",
    "quiebre": "Ruptura o separación de algo.",
    "quitar": "Remover o hacer desaparecer algo.",
    "quiste": "Tumor o bolsa anormal llena de líquido o material semisólido.",
    "quijada": "Parte de la cara que contiene los dientes.",
    "quinteto": "Conjunto de cinco músicos o cinco piezas musicales.",
    "quorum": "Número mínimo de miembros necesarios para que una reunión sea válida.",
    "quinto": "Que corresponde a la quinta parte de algo.",
    "quintuple": "Que se multiplica por cinco.",
    "quimio": "Abreviatura de quimioterapia, tratamiento para combatir el cáncer.",
    "quiosco": "Pequeña construcción donde se venden periódicos o refrescos.",
    "químico": "Persona que se dedica a la química.",
    "quilt": "Cobija o colcha hecha de capas de tela acolchadas.",
    "quinto": "División de algo en cinco partes iguales.",
    "quiebra": "Situación en la que una empresa no puede cumplir con sus deudas.",
    "quimio": "Abreviatura de quimioterapia.",

    "rápido": "Que se mueve o actúa con gran velocidad.",
    "río": "Corriente natural de agua que fluye.",
    "roca": "Material sólido que forma parte de la corteza terrestre.",
    "ratón": "Roedor pequeño que suele vivir cerca de los humanos.",
    "rey": "Monarca que ejerce el poder en un reino.",
    "reina": "Mujer que es monarca o consorte de un rey.",
    "risa": "Expresión de alegría que se manifiesta mediante sonidos y movimientos faciales.",
    "remedio": "Sustancia que se utiliza para curar enfermedades.",
    "recuerdo": "Representación mental de una experiencia pasada.",
    "regalo": "Obsequio que se hace a alguien.",
    "ruido": "Sonido fuerte o desagradable.",
    "revolución": "Cambio radical en la estructura de una sociedad o sistema político.",
    "ratón": "Dispositivo utilizado para interactuar con la computadora.",
    "rebaja": "Reducción del precio de un producto.",
    "retrato": "Representación visual de una persona, especialmente en pintura o fotografía.",
    "receta": "Instrucciones para preparar un plato o medicamento.",
    "respeto": "Consideración y atención hacia los demás.",
    "reflejo": "Imagen que se ve en un espejo o superficie reflectante.",
    "resistencia": "Capacidad de un material para soportar fuerzas sin romperse.",
    "región": "Área o espacio geográfico con características particulares.",
    "rumor": "Información no confirmada que circula entre las personas.",
    "raíz": "Parte subterránea de una planta que absorbe nutrientes.",
    "repetir": "Decir o hacer algo nuevamente.",
    "rincón": "Esquina o parte de un espacio cerrado.",
    "relación": "Vínculo o conexión entre personas o cosas.",

    "sol": "Estrella que da luz y calor a la Tierra.",
    "silla": "Mueble diseñado para sentarse, generalmente con respaldo.",
    "sal": "Sustancia cristalina utilizada como condimento y conservante.",
    "sopa": "Comida líquida hecha al hervir ingredientes en agua.",
    "sonido": "Vibración que se transmite a través de un medio y se percibe por el oído.",
    "sueño": "Estado de reposo en el que la mente se encuentra activa.",
    "sabiduría": "Conocimiento profundo y juicio sensato.",
    "serpiente": "Reptil alargado y sin extremidades.",
    "sangre": "Líquido rojo que circula por el cuerpo de los seres vivos.",
    "silencio": "Ausencia de sonido o ruido.",
    "sabor": "Percepción de los alimentos a través de los sentidos.",
    "salud": "Estado de completo bienestar físico, mental y social.",
    "semilla": "Parte de una planta que puede germinar y crecer.",
    "sombrero": "Accesorio que se lleva en la cabeza para protección o estilo.",
    "suerte": "Circunstancia favorable o desafortunada que se presenta en la vida.",
    "sustancia": "Materia de la que están hechos los objetos.",
    "símbolo": "Signo que representa o significa algo.",
    "sistema": "Conjunto de partes interrelacionadas que forman un todo.",
    "sociedad": "Conjunto de individuos que comparten una cultura y organización social.",
    "sentido": "Capacidad de percibir estímulos a través de los sentidos.",
    "suspenso": "Estado de incertidumbre o expectativa.",
    "suelo": "Capa superficial de la Tierra donde crecen las plantas.",
    "secreto": "Información que no se revela a otros.",
    "sabana": "Pradera extensa de hierba, común en regiones tropicales.",
    "sílaba": "Unidad de sonido en una palabra.",

    "tiempo": "Dimensión en la que se miden los sucesos.",
    "tierra": "Planeta en el que vivimos; también se refiere al suelo.",
    "taza": "Vajilla con un asa, utilizada para beber líquidos.",
    "trabajo": "Actividad realizada a cambio de un salario.",
    "teatro": "Lugar donde se representan obras dramáticas.",
    "tigre": "Gran felino de pelaje anaranjado con rayas negras.",
    "técnica": "Método o habilidad para realizar una tarea.",
    "tela": "Material tejido que se utiliza para confeccionar prendas.",
    "tornado": "Violento fenómeno meteorológico que forma una columna de aire en rotación.",
    "tarea": "Trabajo que se asigna a una persona para completar.",
    "tranquilo": "Estado de calma y serenidad.",
    "turismo": "Actividad de viajar por placer o recreo.",
    "templo": "Edificio dedicado al culto religioso.",
    "tendencia": "Inclinación o propensión hacia algo.",
    "técnico": "Persona especializada en un área específica.",
    "tristeza": "Emoción que se experimenta ante situaciones negativas.",
    "tránsito": "Movimiento de personas o vehículos de un lugar a otro.",
    "transformación": "Cambio en la forma, estructura o apariencia de algo.",
    "terapia": "Tratamiento para aliviar enfermedades o problemas de salud.",
    "tecnología": "Conjunto de conocimientos y técnicas aplicadas a la producción.",
    "teléfono": "Dispositivo utilizado para la comunicación a distancia.",
    "triángulo": "Figura geométrica de tres lados.",
    "travesía": "Viaje o recorrido a través de un lugar.",
    "toro": "Animal macho de la especie bovina.",
    "trompeta": "Instrumento musical de viento que produce un sonido agudo.",
    "túnel": "Paso subterráneo o cavidad a través de la tierra.",

    "unicornio": "Criatura mitológica con un solo cuerno en la frente.",
    "universo": "Conjunto de todo lo que existe, incluyendo planetas, estrellas y galaxias.",
    "utilidad": "Capacidad de algo para satisfacer necesidades o deseos.",
    "último": "Que se encuentra en la posición final en una serie.",
    "universidad": "Institución de educación superior que ofrece títulos académicos.",
    "unidad": "Conjunto que forma un todo; también se refiere a una parte indivisible.",
    "urgente": "Que requiere atención inmediata.",
    "usuario": "Persona que utiliza un servicio o sistema.",
    "ubicar": "Colocar o situar algo en un lugar específico.",
    "ud": "Forma de tratamiento formal en español, utilizada para referirse a alguien con respeto.",
    "ultravioleta": "Radiación electromagnética con una longitud de onda más corta que la luz visible.",
    "unir": "Juntar o combinar cosas en un solo conjunto.",
    "utopía": "Idea o plan que describe una sociedad perfecta.",
    "ultimátum": "Exigencia final que debe cumplirse en un plazo determinado.",
    "ultrasonido": "Sonido con una frecuencia superior al límite del oído humano.",
    "ubicuidad": "Cualidad de estar presente en varios lugares a la vez.",
    "usanza": "Costumbre o práctica habitual de una comunidad.",
    "unilateral": "Que se realiza o afecta a una sola parte.",
    "ura": "Palabra que se refiere a una parte de la boca de algunos animales.",
    "uñeta": "Parte de una uña o garra.",
    "universidad": "Institución de educación superior que otorga grados académicos.",
    "urgencia": "Situación que requiere atención inmediata.",
    "usura": "Práctica de cobrar intereses excesivos por préstamos.",
    "utensilio": "Objeto utilizado para realizar una actividad, especialmente en la cocina.",
    "urbanismo": "Disciplina que estudia el desarrollo y ordenamiento de las ciudades.",

    "viento": "Movimiento del aire en la atmósfera.",
    "vacaciones": "Período de tiempo en el que se interrumpen las actividades laborales o escolares.",
    "vínculo": "Conexión o relación entre dos o más cosas.",
    "valiente": "Persona que muestra coraje y determinación ante el peligro.",
    "vegetal": "Organismo que pertenece al reino de las plantas.",
    "vulcano": "Volcán; montaña que expulsa lava y cenizas.",
    "vehículo": "Medio de transporte, como un coche o una bicicleta.",
    "vendedor": "Persona que ofrece productos o servicios a cambio de dinero.",
    "vista": "Sentido que permite percibir el entorno a través de los ojos.",
    "vacío": "Estado de no contener nada; ausencia de contenido.",
    "venerar": "Mostrar gran respeto y devoción hacia alguien o algo.",
    "vibración": "Movimiento rápido y oscilante de un objeto.",
    "vivienda": "Lugar donde vive una persona o grupo de personas.",
    "valor": "Importancia o utilidad de algo.",
    "vuelta": "Acción de girar o retornar al lugar de origen.",
    "ventana": "Abertura en una pared que permite la entrada de luz y aire.",
    "vocabulario": "Conjunto de palabras que se utilizan en un idioma o por una persona.",
    "verso": "Línea de un poema.",
    "vulgar": "Que es común o corriente; también se refiere a algo grosero.",
    "variedad": "Diferencia o diversidad entre cosas del mismo tipo.",
    "votar": "Ejercer el derecho a elegir en una elección.",
    "vínculo": "Relación o conexión entre dos o más entidades.",
    "vejez": "Etapa de la vida que sigue a la adultez.",
    "vanguardia": "Movimiento que se encuentra en la parte más avanzada de algo.",
    "viñeta": "Dibujo o ilustración que acompaña un texto.",
    "vincular": "Unir o conectar cosas o personas.",

    "web": "Conjunto de páginas interconectadas que se acceden a través de Internet.",
    "whisky": "Bebida alcohólica destilada a partir de cereales.",
    "wafle": "Pastel plano, ligero y crujiente, a menudo con forma de rejilla.",
    "walking": "Término en inglés que significa caminar.",
    "watch": "Reloj portátil que se lleva en la muñeca.",
    "wolverine": "Mamífero carnívoro de la familia de los mustélidos, conocido por su fuerza.",
    "wifi": "Tecnología que permite la conexión inalámbrica a redes de computadoras.",
    "window": "Abertura en un edificio que permite la entrada de luz y aire.",
    "worm": "Gusano; invertebrado alargado y blando que vive en el suelo.",
    "wallet": "Cartera o funda para llevar dinero y tarjetas.",
    "whistle": "Silbato; instrumento para producir un sonido agudo al soplar.",
    "waltz": "Baile en compás de 3/4 que se caracteriza por su movimiento suave.",
    "wonder": "Maravilla; sensación de asombro ante algo extraordinario.",
    "witness": "Persona que observa un evento y puede dar testimonio de él.",
    "wilderness": "Área natural que no ha sido modificada por el ser humano.",
    "wisdom": "Capacidad de tomar decisiones acertadas basadas en el conocimiento.",
    "workshop": "Taller donde se realizan trabajos manuales o técnicos.",
    "world": "El planeta Tierra y todo lo que contiene.",
    "wilderness": "Zona salvaje no urbanizada.",
    "wrist": "Parte del cuerpo que conecta la mano con el antebrazo.",
    "waist": "Parte del cuerpo entre el pecho y las caderas.",
    "word": "Unidad de lenguaje que tiene significado.",
    "wager": "Apuesta; acuerdo entre dos partes sobre el resultado de un evento.",
    "whirlpool": "Remolino de agua que gira en un lugar específico.",
    "wavelength": "Distancia entre dos crestas de una onda, especialmente en la luz.",

    "xilófono": "Instrumento musical de percusión compuesto por láminas de madera.",
    "xenofobia": "Miedo o rechazo hacia personas de otros países o culturas.",
    "xenón": "Gas noble, incoloro e inodoro, utilizado en iluminación.",
    "xilografía": "Técnica de impresión que utiliza madera tallada.",
    "xenón": "Elemento químico de la tabla periódica con símbolo Xe.",
    "xenofonía": "Fenómeno de repetición de palabras de otros idiomas.",
    "xilografía": "Arte de grabar en madera.",
    "xerografía": "Método de impresión basado en la fotocopia.",
    "xenón": "Gas noble usado en lámparas de descarga.",
    "xiphoides": "Parte del esternón en la anatomía humana.",
    "xilofono": "Instrumento musical de láminas de madera, similar al xilófono.",
    "xantofila": "Pigmento amarillo presente en algunas plantas.",
    "xiloma": "Término relacionado con tejidos vegetales.",
    "xenobiología": "Estudio de la vida en otros planetas.",
    "xenotexto": "Texto que incorpora elementos de otras culturas.",
    "xilóide": "Relativo a la madera o sus propiedades.",
    "xalapa": "Capital del estado de Veracruz, en México.",
    "xenolitio": "Roca que se encuentra dentro de otra roca.",
    "xilófono": "Instrumento musical de percusión que produce sonidos al ser golpeado.",
    "xerófilo": "Planta adaptada a vivir en condiciones secas.",
    "xenopatología": "Estudio de enfermedades en organismos no nativos.",
    "xenofilia": "Apreciación y atracción hacia culturas extranjeras.",
    "xilografía": "Técnica de grabado en madera.",
    "xilófono": "Instrumento musical de percusión con láminas de madera.",
    "xilófono": "Instrumento musical que produce sonidos al ser percutido.",
    "xenotransplante": "Trasplante de órganos de una especie a otra.",

    "yate": "Embarcación de recreo, generalmente de lujo.",
    "yogur": "Producto lácteo obtenido por fermentación de la leche.",
    "yuca": "Planta tropical cuyas raíces son comestibles.",
    "yema": "Parte interna del huevo; también se refiere al brote de una planta.",
    "yacimiento": "Lugar donde se encuentra una cantidad significativa de un recurso natural.",
    "yeti": "Criatura mitológica del Himalaya, también conocida como el abominable hombre de las nieves.",
    "yo": "Pronombre que se utiliza para referirse a uno mismo.",
    "yodo": "Elemento químico utilizado en medicina y como desinfectante.",
    "yarn": "Término en inglés que significa hilo o lana.",
    "yugo": "Instrumento que se usa para unir a los animales de tiro.",
    "yuxtaposición": "Colocación de dos elementos uno al lado del otro.",
    "yacer": "Estar tendido o en una posición horizontal.",
    "yihad": "Lucha o esfuerzo en el camino de Dios, en un contexto religioso.",
    "yacimiento": "Lugar donde se extraen recursos, como minerales o fósiles.",
    "yogui": "Persona que practica el yoga de forma profunda.",
    "yermo": "Terreno deshabitado y sin cultivar.",
    "yare": "Término antiguo que significa ágil o ligero.",
    "yugo": "Aparato que se coloca sobre el cuello de los animales de carga.",
    "yoga": "Sistema de ejercicios y técnicas de meditación.",
    "yuxtaposición": "Situación en la que dos elementos se colocan uno junto al otro.",
    "yacimiento": "Lugar donde se encuentra una concentración de minerales o fósiles.",
    "yema": "Parte del huevo que contiene el embrión.",
    "yogurt": "Producto lácteo fermentado.",
    "yeti": "Ser mitológico que se dice habita en el Himalaya.",
    "yate": "Vela o motor que se utiliza para navegar por placer.",

    "zorro": "Mamífero carnívoro de la familia de los cánidos, conocido por su astucia.",
    "zapato": "Calzado que cubre y protege el pie.",
    "zoología": "Ciencia que estudia a los animales.",
    "zanahoria": "Planta comestible de raíz anaranjada, rica en vitamina A.",
    "zen": "Escuela de budismo que enfatiza la meditación.",
    "zafiro": "Mineral precioso, variante del corindón, de color azul.",
    "zodiaco": "Cinturón celeste dividido en doce partes, asociado con la astrología.",
    "zumo": "Líquido extraído de frutas o verduras.",
    "zarzuela": "Género musical español que combina canto y diálogo hablado.",
    "zancada": "Paso largo que se da al caminar o correr.",
    "zorro": "Animal conocido por su inteligencia y agilidad.",
    "zinc": "Elemento químico, metal usado en la galvanización.",
    "zócalo": "Base o parte inferior de un objeto; también se refiere a la plaza principal de una ciudad.",
    "zenit": "Punto más alto en el cielo en relación a un observador.",
    "zócalo": "Fondo o base de una construcción, o la plaza central de una ciudad.",
    "zafra": "Período de cosecha de la caña de azúcar.",
    "zarigüeya": "Marsupial que se encuentra en América, conocido por su capacidad de jugar muerto.",
    "zuñido": "Sonido agudo y continuo que produce un objeto al moverse rápidamente.",
    "zarza": "Planta espinosa que produce frutos, como las moras.",
    "zancudo": "Insecto de gran tamaño, conocido por su capacidad de picar.",
    "zurrón": "Saco grande utilizado para transportar objetos.",
    "zoológico": "Lugar donde se exhiben y cuidan animales de diversas especies.",
    "zoonosis": "Enfermedades que se transmiten de animales a humanos.",
    "zodiacal": "Relativo al zodiaco.",
    "zafado": "Persona que actúa de manera descarada o sin vergüenza.",

    "perro": "Mamífero doméstico, conocido como el mejor amigo del hombre.",
    "hola": "Saludo informal usado para iniciar una conversación.",
    "que hubo": "Expresión coloquial utilizada para preguntar qué ha pasado o cómo está alguien.",
    "horrible": "Que causa horror o es extremadamente malo.",
    "esternocleidomastoideo": "Permite la rotación y flexión de la cabeza.",
    "estupefacto": "Asombrado o sorprendido, generalmente de forma negativa.",
};

const searchInput = document.getElementById('search');
const resultDiv = document.getElementById('result');

searchInput.addEventListener('input', function() {
    const query = searchInput.value.toLowerCase();
    resultDiv.classList.add('hidden');
    resultDiv.innerHTML = '';

    if (dictionary[query]) {
        resultDiv.innerHTML = `
            <div class="word">${query}</div>
            <div class="definition">${dictionary[query]}</div>
        `;
        setTimeout(() => {
            resultDiv.classList.remove('hidden');
            resultDiv.classList.add('visible');
        }, 200);
    } else if (query) {
        resultDiv.innerHTML = `<div class="word">No se encontró la palabra "${query}".</div>`;
        resultDiv.classList.remove('hidden');
        resultDiv.classList.add('visible');
    }
});